repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.14.2
    hooks:
      - id: check-github-workflows
