repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.0
    hooks:
      - id: check-github-workflows
