[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Armen Zambrano G.", email = "armenzg@sentry.io"},
]
license-expression = "MIT"
dependencies = [
    "flask>=2.0.3",
    "sentry-sdk>=1.5.8",
]
requires-python = ">=3.8"

[project.urls]
Homepage = ""

[project.optional-dependencies]
[tool.pdm]

[tool.pdm.scripts]
start = "flask runserver"
test = "pytest"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.1",
]
[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
