[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Armen Zambrano G.", email = "armenzg@sentry.io"},
]
license-expression = "MIT"
dependencies = [
    "Django==3.2",
]
requires-python = ">=3.8"

[project.urls]
Homepage = ""
[tool.pdm]

[tool.pdm.scripts]
start = "python src/manage.py runserver"
migrate = "python src/manage.py migrate"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
