name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t docker-app .

      - name: Test starting
        run: |
          docker run -d --rm docker-app
          docker stop $(docker ps -aq)

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Set up
        run: |
          pip install tox

      - name: Run tests
        run: |
          tox

      - uses: codecov/codecov-action@v2
        with:
          verbose: true # optional (default = false)

  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Set up
        run: |
          pip install wheel
          pip install pre-commit

      - name: Install hooks
        run: |
          pre-commit install

      - name: Run hooks
        run: |
          pre-commit run --all-files
